version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: territorium_db
    volumes:
      - pg-data-v3:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "3100:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://root:secretpassword@db:5432/territorium_db
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    ports:
      - "3200:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pg-data-v3: